# Generated by Django 6.1.1 on 2026-09-06 01:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_name', models.CharField(default='PeoplePay360', max_length=60)),
                ('company_name', models.CharField(blank=True, max_length=120)),
                ('logo_b64', models.TextField(blank=True)),
                ('logo_mime', models.CharField(blank=True, max_length=40)),
                ('logo_filename', models.CharField(blank=True, max_length=255)),
                ('watermark_b64', models.TextField(blank=True)),
                ('watermark_mime', models.CharField(blank=True, max_length=40)),
                ('watermark_filename', models.CharField(blank=True, max_length=255)),
                ('watermark_opacity', models.PositiveSmallIntegerField(default=4)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branding_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'branding',
            },
        ),
    ]
