# Generated by Django 6.1.1 on 2026-09-05 05:14

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payrun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('employee_type', models.CharField(blank=True, max_length=20)),
                ('state', models.CharField(choices=[('DRAFT', 'Draft'), ('COMPUTED', 'Computed'), ('VALIDATED', 'Validated'), ('PAID', 'Paid')], default='DRAFT', max_length=12)),
                ('computed_at', models.DateTimeField(blank=True, null=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payruns', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payruns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('worked_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('expected_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('lop_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('state', models.CharField(choices=[('DRAFT', 'Draft'), ('COMPUTED', 'Computed'), ('VALIDATED', 'Validated'), ('PAID', 'Paid')], default='DRAFT', max_length=12)),
                ('number', models.CharField(blank=True, max_length=30, unique=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payslips', to='employees.contract')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='employees.employee')),
                ('payrun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='payroll.payrun')),
            ],
            options={
                'ordering': ['employee__first_name'],
            },
        ),
        migrations.CreateModel(
            name='PayslipWarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('AC_MISSING', 'Bank account missing'), ('DUPLICATE', 'Duplicate payslip'), ('NO_CONTRACT', 'No contract for period'), ('NEGATIVE_NET', 'Negative net salary'), ('NO_STRUCTURE', 'No salary structure'), ('RULE_ERROR', 'Salary rule error')], max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('WARNING', 'Warning'), ('ERROR', 'Error')], default='WARNING', max_length=8)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payroll_warnings', to='employees.employee')),
                ('payrun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to='payroll.payrun')),
                ('payslip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to='payroll.payslip')),
            ],
            options={
                'ordering': ['severity', 'code'],
            },
        ),
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structures', to='core.company')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SalaryRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('BASIC', 'Basic'), ('ALLOWANCE', 'Allowance'), ('GROSS', 'Gross'), ('DEDUCTION', 'Deduction'), ('NET', 'Net')], max_length=12)),
                ('sequence', models.IntegerField(default=10)),
                ('computation', models.CharField(choices=[('FIXED', 'Fixed Amount'), ('PERCENTAGE', 'Percentage of Wage'), ('FORMULA', 'Formula / Python Code')], default='FIXED', max_length=12)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('percentage_base', models.CharField(blank=True, help_text='Rule code the percentage applies to. Blank = contract wage.', max_length=20)),
                ('formula', models.TextField(blank=True)),
                ('condition', models.TextField(blank=True, help_text='Optional expression; blank means always applies.')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=6)),
                ('appears_on_payslip', models.BooleanField(default=True)),
                ('is_employer_cost', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='payroll.salarystructure')),
            ],
            options={
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.AddField(
            model_name='payslip',
            name='salary_structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='payroll.salarystructure'),
        ),
        migrations.AddField(
            model_name='payrun',
            name='salary_structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payruns', to='payroll.salarystructure'),
        ),
        migrations.CreateModel(
            name='PayslipLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('BASIC', 'Basic'), ('ALLOWANCE', 'Allowance'), ('GROSS', 'Gross'), ('DEDUCTION', 'Deduction'), ('NET', 'Net')], max_length=12)),
                ('sequence', models.IntegerField(default=10)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=6)),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='payroll.payslip')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payslip_lines', to='payroll.salaryrule')),
            ],
            options={
                'ordering': ['sequence', 'id'],
                'constraints': [models.UniqueConstraint(fields=('payslip', 'code'), name='uniq_line_code_per_payslip')],
            },
        ),
        migrations.AddConstraint(
            model_name='salaryrule',
            constraint=models.UniqueConstraint(fields=('structure', 'code'), name='uniq_rule_code_per_structure'),
        ),
        migrations.AddConstraint(
            model_name='payslip',
            constraint=models.UniqueConstraint(fields=('employee', 'period_start', 'period_end'), name='uniq_payslip_per_employee_period'),
        ),
        migrations.AddConstraint(
            model_name='payrun',
            constraint=models.CheckConstraint(condition=models.Q(('period_end__gte', models.F('period_start'))), name='payrun_period_ordered'),
        ),
    ]
