# Generated by Django 6.1.1 on 2026-09-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslipline',
            name='appears_on_payslip',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='payslipline',
            name='is_employer_cost',
            field=models.BooleanField(default=False),
        ),
    ]
