# Generated by Django 6.1.1 on 2026-09-05 05:14

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeOffType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('unit', models.CharField(choices=[('DAYS', 'Days'), ('HOURS', 'Hours')], default='DAYS', max_length=6)),
                ('requires_allocation', models.BooleanField(default=True)),
                ('approval', models.CharField(choices=[('NONE', 'No Validation'), ('MANAGER', 'By Manager'), ('OFFICER', 'By Time Off Officer')], default='MANAGER', max_length=10)),
                ('is_paid', models.BooleanField(default=True)),
                ('work_entry_code', models.CharField(blank=True, max_length=40)),
                ('color', models.CharField(default='blue', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('allocated', models.DecimalField(decimal_places=2, max_digits=6)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('state', models.CharField(choices=[('DRAFT', 'Draft'), ('TO_APPROVE', 'To Approve'), ('APPROVED', 'Approved'), ('REFUSED', 'Refused')], default='DRAFT', max_length=12)),
                ('description', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='employees.employee')),
                ('time_off_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='timeoff.timeofftype')),
            ],
            options={
                'ordering': ['-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='TimeOffRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('duration', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('half_day', models.CharField(blank=True, choices=[('FIRST', 'First Half'), ('SECOND', 'Second Half')], max_length=6)),
                ('state', models.CharField(choices=[('DRAFT', 'Draft'), ('TO_APPROVE', 'To Approve'), ('APPROVED', 'Approved'), ('REFUSED', 'Refused'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=12)),
                ('reason', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('allocation_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consuming_requests', to='timeoff.allocation')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_timeoff', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeoff_requests', to='employees.employee')),
                ('time_off_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='timeoff.timeofftype')),
            ],
            options={
                'ordering': ['-date_from'],
                'indexes': [models.Index(fields=['employee', 'state', 'date_from'], name='timeoff_tim_employe_96e261_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('date_to__gte', models.F('date_from'))), name='timeoff_dates_ordered')],
            },
        ),
        migrations.AddIndex(
            model_name='allocation',
            index=models.Index(fields=['employee', 'time_off_type', 'state'], name='timeoff_all_employe_827e16_idx'),
        ),
        migrations.AddConstraint(
            model_name='allocation',
            constraint=models.CheckConstraint(condition=models.Q(('allocated__gt', 0)), name='allocation_positive'),
        ),
    ]
