# Generated by Django 6.1.1 on 2026-09-05 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('employees', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecuritySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enforce_network_policy', models.BooleanField(default=False, help_text='Refuse sign-in from outside the configured networks.')),
                ('enforce_network_on_punch', models.BooleanField(default=True, help_text='Refuse attendance check-in from outside those networks, even when general sign-in is unrestricted.')),
                ('max_failed_logins', models.PositiveIntegerField(default=5)),
                ('lockout_minutes', models.PositiveIntegerField(default=15)),
                ('session_idle_minutes', models.PositiveIntegerField(default=480, help_text='Sign a token out after this long without use.')),
                ('session_max_hours', models.PositiveIntegerField(default=24, help_text='Absolute lifetime of a token, however active.')),
                ('password_min_length', models.PositiveIntegerField(default=8)),
                ('bind_session_to_ip', models.BooleanField(default=False, help_text='Invalidate a token if it is presented from a new address.')),
            ],
            options={
                'verbose_name': 'security settings',
                'verbose_name_plural': 'security settings',
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(db_index=True, max_length=254)),
                ('ip_address', models.CharField(blank=True, db_index=True, max_length=45)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('succeeded', models.BooleanField(default=False)),
                ('reason', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'created_at'], name='accounts_lo_email_351ee0_idx')],
            },
        ),
        migrations.CreateModel(
            name='NetworkPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('cidr', models.CharField(help_text='IPv4 or IPv6 network, e.g. 192.168.1.0/24 or 203.0.113.7/32', max_length=64)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('role', models.ForeignKey(blank=True, help_text='Leave empty to apply to every account.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='network_policies', to='accounts.role')),
            ],
            options={
                'verbose_name_plural': 'network policies',
                'ordering': ['role__code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_email', models.CharField(blank=True, max_length=254)),
                ('action', models.CharField(choices=[('SIGN_IN', 'Signed in'), ('SIGN_IN_FAILED', 'Sign-in refused'), ('SIGN_OUT', 'Signed out'), ('PASSWORD_CHANGED', 'Password changed'), ('ROLES_CHANGED', 'Roles changed'), ('USER_CREATED', 'User created'), ('USER_DEACTIVATED', 'User deactivated'), ('PROFILE_EDITED', 'Profile edited'), ('PROFILE_CHANGE_REQUESTED', 'Profile change requested'), ('PROFILE_CHANGE_DECIDED', 'Profile change decided'), ('ATTENDANCE_PUNCH', 'Attendance punch'), ('ATTENDANCE_CORRECTED', 'Attendance corrected'), ('TIMEOFF_DECIDED', 'Time off decided'), ('PAYRUN_STATE', 'Payrun state change'), ('SECURITY_CHANGED', 'Security settings changed')], db_index=True, max_length=32)),
                ('summary', models.CharField(max_length=300)),
                ('target_type', models.CharField(blank=True, max_length=40)),
                ('target_id', models.CharField(blank=True, max_length=40)),
                ('ip_address', models.CharField(blank=True, max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='accounts_au_action_c683b9_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProfileChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.CharField(max_length=40)),
                ('old_value', models.CharField(blank=True, max_length=200)),
                ('new_value', models.CharField(blank=True, max_length=200)),
                ('reason', models.TextField(blank=True)),
                ('state', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REFUSED', 'Refused'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.CharField(blank=True, max_length=200)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_change_requests', to='employees.employee')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_changes_raised', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_changes_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employee', 'state'], name='accounts_pr_employe_0fb2a5_idx')],
            },
        ),
    ]
