# Generated by Django 6.1.1 on 2026-09-05 15:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_securitysetting_loginattempt_networkpolicy_auditlog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionActivity',
            fields=[
                ('token_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('ip_address', models.CharField(blank=True, max_length=45)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_activity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'session activity',
                'ordering': ['-last_used'],
            },
        ),
    ]
