# Generated by Django 6.1.1 on 2026-09-06 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('SIGN_IN', 'Signed in'), ('SIGN_IN_FAILED', 'Sign-in refused'), ('SIGN_OUT', 'Signed out'), ('PASSWORD_CHANGED', 'Password changed'), ('ROLES_CHANGED', 'Roles changed'), ('USER_CREATED', 'User created'), ('USER_DEACTIVATED', 'User deactivated'), ('PROFILE_EDITED', 'Profile edited'), ('PROFILE_CHANGE_REQUESTED', 'Profile change requested'), ('PROFILE_CHANGE_DECIDED', 'Profile change decided'), ('ATTENDANCE_PUNCH', 'Attendance punch'), ('ATTENDANCE_CORRECTED', 'Attendance corrected'), ('TIMEOFF_DECIDED', 'Time off decided'), ('PAYRUN_STATE', 'Payrun state change'), ('SECURITY_CHANGED', 'Security settings changed'), ('DATA_IMPORTED', 'Roster imported'), ('BRANDING_CHANGED', 'Branding changed'), ('WORKFORCE_BULK', 'Bulk workforce operation')], db_index=True, max_length=32),
        ),
    ]
