# Generated by Django 6.1.1 on 2026-09-05 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target', models.CharField(default='employees', max_length=40)),
                ('state', models.CharField(choices=[('DRAFT', 'Draft'), ('PROFILED', 'Profiled'), ('MAPPED', 'Mapped'), ('PREVIEWED', 'Previewed'), ('IMPORTING', 'Importing'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='DRAFT', max_length=12)),
                ('plan', models.JSONField(blank=True, default=dict)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('llm_used', models.BooleanField(default=False)),
                ('llm_model', models.CharField(blank=True, max_length=80)),
                ('llm_latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_index', models.IntegerField(default=-1)),
                ('column', models.CharField(blank=True, max_length=80)),
                ('severity', models.CharField(choices=[('error', 'Error'), ('warning', 'Warning')], default='warning', max_length=8)),
                ('code', models.CharField(max_length=40)),
                ('message', models.CharField(max_length=300)),
                ('suggestion', models.CharField(blank=True, max_length=300)),
                ('auto_fix', models.CharField(blank=True, max_length=40)),
                ('resolved', models.BooleanField(default=False)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='intelligence.importrun')),
            ],
            options={
                'ordering': ['severity', 'row_index'],
            },
        ),
        migrations.CreateModel(
            name='ImportSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('original_filename', models.CharField(max_length=255)),
                ('content_b64', models.TextField()),
                ('byte_size', models.PositiveIntegerField(default=0)),
                ('sheet_name', models.CharField(blank=True, max_length=120)),
                ('encoding', models.CharField(blank=True, max_length=24)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('column_count', models.PositiveIntegerField(default=0)),
                ('header_row_index', models.PositiveIntegerField(default=0)),
                ('junk_rows_above', models.PositiveIntegerField(default=0)),
                ('notes', models.JSONField(blank=True, default=list)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_sources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='importrun',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='intelligence.importsource'),
        ),
    ]
