# Generated by Django 6.1.1 on 2026-09-05 23:03

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BondTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=140)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('duration_months', models.PositiveSmallIntegerField(default=24)),
                ('recovery_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('notice_days', models.PositiveSmallIntegerField(default=30)),
                ('body', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Playbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('trigger', models.CharField(choices=[('TENURE_REACHED', 'Tenure reached'), ('CONTRACT_ENDING', 'Contract ending'), ('BOND_EXPIRING', 'Bond expiring'), ('PROBATION_ENDING', 'Probation ending'), ('NO_BANK_ACCOUNT', 'No bank account')], max_length=20)),
                ('trigger_params', models.JSONField(blank=True, default=dict)),
                ('criteria', models.JSONField(blank=True, default=dict)),
                ('action', models.CharField(choices=[('NOTIFY', 'Raise a reminder'), ('PROPOSE_INCREMENT', 'Propose an increment'), ('FLAG_REVIEW', 'Flag for review')], default='NOTIFY', max_length=20)),
                ('action_params', models.JSONField(blank=True, default=dict)),
                ('active', models.BooleanField(default=True)),
                ('nl_prompt', models.TextField(blank=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playbooks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=140)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('criteria', models.JSONField(default=dict)),
                ('source', models.CharField(choices=[('manual', 'Built by hand'), ('ai', 'Interpreted from a sentence')], default='manual', max_length=8)),
                ('nl_prompt', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='segments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BulkOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=160)),
                ('kind', models.CharField(choices=[('INCREMENT', 'Increment'), ('EXIT', 'Offboarding'), ('TRANSFER', 'Transfer'), ('BOND_ISSUE', 'Issue bonds')], max_length=12)),
                ('state', models.CharField(choices=[('DRAFT', 'Draft'), ('PREVIEWED', 'Previewed'), ('EXECUTED', 'Executed'), ('FAILED', 'Failed')], default='DRAFT', max_length=10)),
                ('criteria', models.JSONField(blank=True, default=dict)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('preview', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_operations', to=settings.AUTH_USER_MODEL)),
                ('segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='workforce.segment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('SIGNED', 'Signed'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('BREACHED', 'Breached'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('duration_months', models.PositiveSmallIntegerField(default=24)),
                ('recovery_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('notice_days', models.PositiveSmallIntegerField(default=30)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('signed_name', models.CharField(blank=True, max_length=160)),
                ('breach_date', models.DateField(blank=True, null=True)),
                ('breach_note', models.CharField(blank=True, max_length=300)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonds', to='employees.employee')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonds_issued', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonds', to='workforce.bondtemplate')),
            ],
            options={
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['state', 'end_date'], name='workforce_b_state_49adb6_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlaybookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fired_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('detail', models.CharField(blank=True, max_length=400)),
                ('acknowledged', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playbook_events', to='employees.employee')),
                ('playbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='workforce.playbook')),
            ],
            options={
                'ordering': ['-fired_at'],
                'constraints': [models.UniqueConstraint(fields=('playbook', 'employee'), name='one_open_event_per_person')],
            },
        ),
    ]
